owner: WorklifeTech        # Your actual GitHub username/org
repo: Uptime               # Exact repo name (case-sensitive)

sites:
  - name: Cal.com (Howdy)
    url: https://cal.howdy.care
    
  - name: Production portal backend
    url: https://api-ne1.worklifebarometer.com/api/ping

  - name: Production portal performance test
    url: https://api-ne1.worklifebarometer.com/api/ping/performance

  - name: Production portal frontend
    url: https://portal.howdy.care

  - name: UAT portal backend
    url: https://wlb-uat-ne1-api.azurewebsites.net/api/ping

  - name: UAT portal performance test
    url: https://wlb-uat-ne1-api.azurewebsites.net/api/ping/performance

  - name: UAT portal frontend
    url: https://wlb-uat-ne1-dashboard.azurewebsites.net/

  - name: App API
    url: https://app.worklifebarometer.com/api/ping

status-website:
  # You don’t have a custom domain (yet), so remove cname:
  # cname: demo.upptime.js.org
  baseUrl: /Uptime          # This MUST match your repo name for GitHub Pages

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Howdy Status
  introTitle: "**Howdy** uptime status"
  introMessage: |
    This page shows uptime and response times for our Cal.com instance at cal.howdy.care.

navbar:
  - title: Status
    href: /
  - title: GitHub
    href: https://github.com/WorklifeTech/Uptime
